# Generated by Django 5.0.14 on 2026-09-21 20:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('invoices', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceCall',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('ringing', 'Ringing'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('no_answer', 'No Answer'), ('busy', 'Busy'), ('cancelled', 'Cancelled')], default='queued', max_length=16)),
                ('provider_call_id', models.CharField(blank=True, default='', max_length=128)),
                ('from_number', models.CharField(blank=True, default='', max_length=32)),
                ('to_number', models.CharField(blank=True, default='', max_length=32)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('recording_url', models.URLField(blank=True, default='')),
                ('cost_minor', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_calls', to='customers.customer')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_calls', to='invoices.invoice')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_set', to='tenancy.organization')),
            ],
            options={
                'db_table': 'voice_calls',
            },
        ),
        migrations.CreateModel(
            name='CallAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt_number', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('ringing', 'Ringing'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('no_answer', 'No Answer'), ('busy', 'Busy'), ('cancelled', 'Cancelled')], default='queued', max_length=16)),
                ('provider_response', models.JSONField(blank=True, default=dict)),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='call_attempts', to='tenancy.organization')),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='voice.voicecall')),
            ],
            options={
                'db_table': 'call_attempts',
                'ordering': ['attempt_number'],
            },
        ),
        migrations.AddIndex(
            model_name='voicecall',
            index=models.Index(fields=['org', 'status'], name='voice_calls_org_id_a18374_idx'),
        ),
    ]
