# Generated by Django 5.0.14 on 2026-09-21 20:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('invoices', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('email', 'Email'), ('voice', 'Voice')], max_length=16)),
                ('template_id', models.CharField(blank=True, default='', max_length=128)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='queued', max_length=16)),
                ('provider_msg_id', models.CharField(blank=True, default='', max_length=128)),
                ('idempotency_key', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('cost_minor', models.IntegerField(blank=True, help_text='Cost in kobo', null=True)),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comm_events', to='customers.customer')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comm_events', to='invoices.invoice')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_set', to='tenancy.organization')),
            ],
            options={
                'db_table': 'communication_events',
                'indexes': [models.Index(fields=['org', 'channel'], name='communicati_org_id_a36464_idx'), models.Index(fields=['org', 'status'], name='communicati_org_id_6535d5_idx')],
            },
        ),
        migrations.CreateModel(
            name='CommunicationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('email', 'Email'), ('voice', 'Voice')], max_length=16)),
                ('enabled', models.BooleanField(default=True)),
                ('opted_out_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comm_preferences', to='customers.customer')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comm_preferences', to='tenancy.organization')),
            ],
            options={
                'db_table': 'communication_preferences',
                'unique_together': {('org', 'customer', 'channel')},
            },
        ),
    ]
