# Generated by Django 5.0.14 on 2026-09-21 22:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Reminder rule', max_length=128)),
                ('trigger', models.CharField(choices=[('before_due', 'Before due'), ('on_due', 'On due date'), ('after_due', 'After due')], default='on_due', max_length=16)),
                ('offset_days', models.IntegerField(default=0, help_text='Days before (negative) or after due date. 0=on due')),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('email', 'Email'), ('voice', 'Voice')], default='whatsapp', max_length=16)),
                ('template', models.TextField(default='Hello {{customer_name}}, invoice {{invoice_number}} for {{amount_due}} is due on {{due_date}}. Pay: {{payment_link}}')),
                ('language', models.CharField(default='auto', help_text='auto=customer preferred, or en/ha/yo/ig', max_length=16)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_set', to='tenancy.organization')),
            ],
            options={
                'db_table': 'reminder_rules',
                'indexes': [models.Index(fields=['org', 'enabled'], name='reminder_ru_org_id_77d685_idx')],
            },
        ),
    ]
