# Generated by Django 5.0.14 on 2026-09-21 20:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('invoices', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('INVOICE_CREATED', 'Invoice Created'), ('REMINDER_SENT', 'Reminder Sent'), ('CUSTOMER_REPLIED', 'Customer Replied'), ('NEGOTIATING', 'Negotiating'), ('PROMISE_MADE', 'Promise Made'), ('PROMISE_DUE', 'Promise Due'), ('PAYMENT_RECEIVED', 'Payment Received'), ('PAYMENT_FAILED', 'Payment Failed'), ('ESCALATED', 'Escalated'), ('HUMAN_HANDOFF', 'Human Handoff'), ('RESOLVED', 'Resolved'), ('CANCELLED', 'Cancelled'), ('FOLLOW_UP', 'Follow Up'), ('OVERDUE_NOTICE', 'Overdue Notice'), ('COLLECTION_CLOSED', 'Collection Closed')], default='INVOICE_CREATED', max_length=32)),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('email', 'Email'), ('voice', 'Voice')], default='whatsapp', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_conversations', to='customers.customer')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_conversations', to='invoices.invoice')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_set', to='tenancy.organization')),
            ],
            options={
                'db_table': 'ai_conversations',
            },
        ),
        migrations.CreateModel(
            name='AIAgentAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tool', models.CharField(help_text='Tool/function name', max_length=128)),
                ('input', models.JSONField(blank=True, default=dict)),
                ('output', models.JSONField(blank=True, default=dict)),
                ('tokens', models.IntegerField(blank=True, null=True)),
                ('cost_minor', models.IntegerField(blank=True, null=True)),
                ('prompt_version', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='ai.aiconversation')),
            ],
            options={
                'db_table': 'ai_agent_actions',
            },
        ),
        migrations.CreateModel(
            name='AIMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System'), ('tool', 'Tool')], default='user', max_length=16)),
                ('content', models.TextField()),
                ('tokens', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai.aiconversation')),
            ],
            options={
                'db_table': 'ai_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromiseToPay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('promise_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('kept', 'Kept'), ('broken', 'Broken'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promises', to='ai.aiconversation')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promises', to='customers.customer')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promises', to='invoices.invoice')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='promises', to='tenancy.organization')),
            ],
            options={
                'db_table': 'promise_to_pay',
            },
        ),
        migrations.AddIndex(
            model_name='aiconversation',
            index=models.Index(fields=['org', 'state'], name='ai_conversa_org_id_94c024_idx'),
        ),
    ]
