# Generated by Django 5.0.14 on 2026-09-21 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_multilingual'),
        ('languages', '0002_rename_cust_lang_hist_org_cust_idx_customer_la_org_id_f733e8_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='customer',
            new_name='customers_org_id_17a619_idx',
            old_name='customers_org_pref_idx',
        ),
        migrations.RenameIndex(
            model_name='customer',
            new_name='customers_preferr_f47187_idx',
            old_name='customers_pref_idx',
        ),
        migrations.AlterField(
            model_name='customer',
            name='preferred_language',
            field=models.ForeignKey(blank=True, db_column='preferred_language', default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='customers_preferred', to='languages.language'),
        ),
    ]
