# Generated by Django 5.0.14 on 2026-09-21 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='customerlanguagehistory',
            new_name='customer_la_org_id_f733e8_idx',
            old_name='cust_lang_hist_org_cust_idx',
        ),
        migrations.RenameIndex(
            model_name='customerlanguagehistory',
            new_name='customer_la_org_id_592b3f_idx',
            old_name='cust_lang_hist_org_idx',
        ),
        migrations.RenameIndex(
            model_name='customerlanguagehistory',
            new_name='customer_la_custome_a936ac_idx',
            old_name='cust_lang_hist_cust_idx',
        ),
    ]
